name: Documenter
on:
    push:
      branches: [master]
      tags: [v*]
    pull_request:

jobs:
    Documenter:
      name: Documentation
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: registry_add
          run: julia -e 'using Pkg; pkg"registry add General https://github.com/HolyLab/HolyLabRegistry.git"'
        - uses: julia-actions/julia-buildpkg@latest
          env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        - uses: julia-actions/julia-docdeploy@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
